const router = require("express").Router();
const registrationController = require("../../controllers/registrationController");
const loginController = require("../../controllers/loginController");
const verifiedUserController = require("../../controllers/verifiedUser");
const verifyToken = require("../../Middleware/verifyToken");
const againActivateController = require("../../controllers/againActivateController");
const resetPassword = require("../../controllers/resetPassword");
const resetCode = require("../../controllers/resetCode");
const matchOTP = require("../../controllers/matchOTP");
const changePassword = require("../../controllers/changePassword");
const getUserController = require("../../controllers/getUserController");
const uploadProfilePictureController = require("../../controllers/uploadProfilePictureControlle");
const uploadCoverPictureController = require("../../controllers/uploadCoverPictureController");
const updateDetailsController = require("../../controllers/updateDetailsController");
const addFriendController = require("../../controllers/addFriendController");
const cancelRequestController = require("../../controllers/cancelRequestController");
const followController = require("../../controllers/followController");
const unFollowController = require("../../controllers/unFollowController");
const acceptRequestController = require("../../controllers/acceptRequestController");
const unFriendController = require("../../controllers/unFriendController");
const deleteRequestController = require("../../controllers/deleteRequestController");

router.post("/", registrationController);
router.post("/activate", verifyToken, verifiedUserController);
router.post("/login", loginController);
router.post("/againActivate", verifyToken, againActivateController);
router.post("/resetPassword", resetPassword);
router.post("/resetCode", resetCode);
router.post("/matchOTP", matchOTP);
router.post("/changePassword", changePassword);
router.get("/user/:username", getUserController);
router.put("/uploadProfilePicture", uploadProfilePictureController);
router.put("/uploadCoverPicture", uploadCoverPictureController);
router.put("/uploadDetails", updateDetailsController);
router.put("/addfriend/:id", addFriendController);
router.put("/cancelrequest/:id", cancelRequestController);
router.put("/follow/:id", followController);
router.put("/unfollow/:id", unFollowController);
router.put("/acceptrequest/:id", acceptRequestController);
router.put("/unfrined/:id", unFriendController);
router.put("/deleterequest/:id", deleteRequestController);

module.exports = router;
